blueprint:
  name: Time-based climate schedule (Multi-Schedule)
  description: >
    Set target temperature of one or more climate entities at specific times
    with support for 3 concurrent schedules.
  domain: automation
  input:
    climate_targets:
      name: Climate entities
      description: One or more climate entities to control (TRVs, Better Thermostat, etc.).
      selector:
        entity:
          domain: climate
          multiple: true

    # -------------------------
    # SCHEDULE 1
    # -------------------------
    s1_name:
      name: "Schedule 1: Name"
      description: Optional name for this schedule (e.g. 'Winter Weekdays').
      default: ""
      selector:
        text: {}

    s1_active:
      name: "Schedule 1: Active"
      description: Enable or disable Schedule 1.
      default: true
      selector:
        boolean: {}

    s1_weekdays:
      name: "Schedule 1: Weekdays"
      description: Days on which Schedule 1 should run.
      default: []
      selector:
        select:
          multiple: true
          options:
            - value: mon
              label: Monday
            - value: tue
              label: Tuesday
            - value: wed
              label: Wednesday
            - value: thu
              label: Thursday
            - value: fri
              label: Friday
            - value: sat
              label: Saturday
            - value: sun
              label: Sunday

    s1_hvac_mode:
      name: "Schedule 1: HVAC Mode"
      description: HVAC mode for Schedule 1.
      default: heat
      selector:
        select:
          options:
            - heat
            - auto
            - cool
            - heat_cool
            - dry
            - fan_only

    s1_t1_enabled:
      name: "S1 Time 1: Enabled"
      default: true
      selector:
        boolean: {}
    s1_t1_time:
      name: "S1 Time 1"
      default: "05:00:00"
      selector:
        time: {}
    s1_t1_temp:
      name: "S1 Temp 1"
      default: 22
      selector:
        number:
          min: 5
          max: 35
          step: 0.5
          unit_of_measurement: "°C"
          mode: box

    s1_t2_enabled:
      name: "S1 Time 2: Enabled"
      default: true
      selector:
        boolean: {}
    s1_t2_time:
      name: "S1 Time 2"
      default: "09:00:00"
      selector:
        time: {}
    s1_t2_temp:
      name: "S1 Temp 2"
      default: 20
      selector:
        number:
          min: 5
          max: 35
          step: 0.5
          unit_of_measurement: "°C"
          mode: box

    s1_t3_enabled:
      name: "S1 Time 3: Enabled"
      default: true
      selector:
        boolean: {}
    s1_t3_time:
      name: "S1 Time 3"
      default: "17:00:00"
      selector:
        time: {}
    s1_t3_temp:
      name: "S1 Temp 3"
      default: 22
      selector:
        number:
          min: 5
          max: 35
          step: 0.5
          unit_of_measurement: "°C"
          mode: box

    s1_t4_enabled:
      name: "S1 Time 4: Enabled"
      default: true
      selector:
        boolean: {}
    s1_t4_time:
      name: "S1 Time 4"
      default: "22:00:00"
      selector:
        time: {}
    s1_t4_temp:
      name: "S1 Temp 4"
      default: 20
      selector:
        number:
          min: 5
          max: 35
          step: 0.5
          unit_of_measurement: "°C"
          mode: box

    # -------------------------
    # SCHEDULE 2
    # -------------------------
    s2_name:
      name: "Schedule 2: Name"
      description: Optional name for this schedule.
      default: ""
      selector:
        text: {}

    s2_active:
      name: "Schedule 2: Active"
      description: Enable or disable Schedule 2.
      default: false
      selector:
        boolean: {}

    s2_weekdays:
      name: "Schedule 2: Weekdays"
      description: Days on which Schedule 2 should run.
      default: []
      selector:
        select:
          multiple: true
          options:
            - value: mon
              label: Monday
            - value: tue
              label: Tuesday
            - value: wed
              label: Wednesday
            - value: thu
              label: Thursday
            - value: fri
              label: Friday
            - value: sat
              label: Saturday
            - value: sun
              label: Sunday

    s2_hvac_mode:
      name: "Schedule 2: HVAC Mode"
      description: HVAC mode for Schedule 2.
      default: heat
      selector:
        select:
          options:
            - heat
            - auto
            - cool
            - heat_cool
            - dry
            - fan_only

    s2_t1_enabled:
      name: "S2 Time 1: Enabled"
      default: false
      selector:
        boolean: {}
    s2_t1_time:
      name: "S2 Time 1"
      default: "06:00:00"
      selector:
        time: {}
    s2_t1_temp:
      name: "S2 Temp 1"
      default: 21
      selector:
        number:
          min: 5
          max: 35
          step: 0.5
          unit_of_measurement: "°C"
          mode: box

    s2_t2_enabled:
      name: "S2 Time 2: Enabled"
      default: false
      selector:
        boolean: {}
    s2_t2_time:
      name: "S2 Time 2"
      default: "08:00:00"
      selector:
        time: {}
    s2_t2_temp:
      name: "S2 Temp 2"
      default: 19
      selector:
        number:
          min: 5
          max: 35
          step: 0.5
          unit_of_measurement: "°C"
          mode: box

    s2_t3_enabled:
      name: "S2 Time 3: Enabled"
      default: false
      selector:
        boolean: {}
    s2_t3_time:
      name: "S2 Time 3"
      default: "16:00:00"
      selector:
        time: {}
    s2_t3_temp:
      name: "S2 Temp 3"
      default: 21
      selector:
        number:
          min: 5
          max: 35
          step: 0.5
          unit_of_measurement: "°C"
          mode: box

    s2_t4_enabled:
      name: "S2 Time 4: Enabled"
      default: false
      selector:
        boolean: {}
    s2_t4_time:
      name: "S2 Time 4"
      default: "23:00:00"
      selector:
        time: {}
    s2_t4_temp:
      name: "S2 Temp 4"
      default: 19
      selector:
        number:
          min: 5
          max: 35
          step: 0.5
          unit_of_measurement: "°C"
          mode: box

    # -------------------------
    # SCHEDULE 3
    # -------------------------
    s3_name:
      name: "Schedule 3: Name"
      description: Optional name for this schedule.
      default: ""
      selector:
        text: {}

    s3_active:
      name: "Schedule 3: Active"
      description: Enable or disable Schedule 3.
      default: false
      selector:
        boolean: {}

    s3_weekdays:
      name: "Schedule 3: Weekdays"
      description: Days on which Schedule 3 should run.
      default: []
      selector:
        select:
          multiple: true
          options:
            - value: mon
              label: Monday
            - value: tue
              label: Tuesday
            - value: wed
              label: Wednesday
            - value: thu
              label: Thursday
            - value: fri
              label: Friday
            - value: sat
              label: Saturday
            - value: sun
              label: Sunday

    s3_hvac_mode:
      name: "Schedule 3: HVAC Mode"
      description: HVAC mode for Schedule 3.
      default: heat
      selector:
        select:
          options:
            - heat
            - auto
            - cool
            - heat_cool
            - dry
            - fan_only

    s3_t1_enabled:
      name: "S3 Time 1: Enabled"
      default: false
      selector:
        boolean: {}
    s3_t1_time:
      name: "S3 Time 1"
      default: "07:00:00"
      selector:
        time: {}
    s3_t1_temp:
      name: "S3 Temp 1"
      default: 20
      selector:
        number:
          min: 5
          max: 35
          step: 0.5
          unit_of_measurement: "°C"
          mode: box

    s3_t2_enabled:
      name: "S3 Time 2: Enabled"
      default: false
      selector:
        boolean: {}
    s3_t2_time:
      name: "S3 Time 2"
      default: "10:00:00"
      selector:
        time: {}
    s3_t2_temp:
      name: "S3 Temp 2"
      default: 18
      selector:
        number:
          min: 5
          max: 35
          step: 0.5
          unit_of_measurement: "°C"
          mode: box

    s3_t3_enabled:
      name: "S3 Time 3: Enabled"
      default: false
      selector:
        boolean: {}
    s3_t3_time:
      name: "S3 Time 3"
      default: "18:00:00"
      selector:
        time: {}
    s3_t3_temp:
      name: "S3 Temp 3"
      default: 20
      selector:
        number:
          min: 5
          max: 35
          step: 0.5
          unit_of_measurement: "°C"
          mode: box

    s3_t4_enabled:
      name: "S3 Time 4: Enabled"
      default: false
      selector:
        boolean: {}
    s3_t4_time:
      name: "S3 Time 4"
      default: "23:00:00"
      selector:
        time: {}
    s3_t4_temp:
      name: "S3 Temp 4"
      default: 18
      selector:
        number:
          min: 5
          max: 35
          step: 0.5
          unit_of_measurement: "°C"
          mode: box

mode: single

triggers:
  # Schedule 1
  - trigger: time
    at: !input s1_t1_time
    id: s1_t1
  - trigger: time
    at: !input s1_t2_time
    id: s1_t2
  - trigger: time
    at: !input s1_t3_time
    id: s1_t3
  - trigger: time
    at: !input s1_t4_time
    id: s1_t4
  # Schedule 2
  - trigger: time
    at: !input s2_t1_time
    id: s2_t1
  - trigger: time
    at: !input s2_t2_time
    id: s2_t2
  - trigger: time
    at: !input s2_t3_time
    id: s2_t3
  - trigger: time
    at: !input s2_t4_time
    id: s2_t4
  # Schedule 3
  - trigger: time
    at: !input s3_t1_time
    id: s3_t1
  - trigger: time
    at: !input s3_t2_time
    id: s3_t2
  - trigger: time
    at: !input s3_t3_time
    id: s3_t3
  - trigger: time
    at: !input s3_t4_time
    id: s3_t4

actions:
  - choose:
      # -----------------------
      # Schedule 1 Actions
      # -----------------------
      - conditions:
          - condition: trigger
            id: s1_t1
          - condition: template
            value_template: "{{ !input s1_active }}"
          - condition: template
            value_template: "{{ !input s1_t1_enabled }}"
          - condition: time
            weekday: !input s1_weekdays
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: !input climate_targets
            data:
              hvac_mode: !input s1_hvac_mode
              temperature: !input s1_t1_temp

      - conditions:
          - condition: trigger
            id: s1_t2
          - condition: template
            value_template: "{{ !input s1_active }}"
          - condition: template
            value_template: "{{ !input s1_t2_enabled }}"
          - condition: time
            weekday: !input s1_weekdays
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: !input climate_targets
            data:
              hvac_mode: !input s1_hvac_mode
              temperature: !input s1_t2_temp

      - conditions:
          - condition: trigger
            id: s1_t3
          - condition: template
            value_template: "{{ !input s1_active }}"
          - condition: template
            value_template: "{{ !input s1_t3_enabled }}"
          - condition: time
            weekday: !input s1_weekdays
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: !input climate_targets
            data:
              hvac_mode: !input s1_hvac_mode
              temperature: !input s1_t3_temp

      - conditions:
          - condition: trigger
            id: s1_t4
          - condition: template
            value_template: "{{ !input s1_active }}"
          - condition: template
            value_template: "{{ !input s1_t4_enabled }}"
          - condition: time
            weekday: !input s1_weekdays
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: !input climate_targets
            data:
              hvac_mode: !input s1_hvac_mode
              temperature: !input s1_t4_temp

      # -----------------------
      # Schedule 2 Actions
      # -----------------------
      - conditions:
          - condition: trigger
            id: s2_t1
          - condition: template
            value_template: "{{ !input s2_active }}"
          - condition: template
            value_template: "{{ !input s2_t1_enabled }}"
          - condition: time
            weekday: !input s2_weekdays
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: !input climate_targets
            data:
              hvac_mode: !input s2_hvac_mode
              temperature: !input s2_t1_temp

      - conditions:
          - condition: trigger
            id: s2_t2
          - condition: template
            value_template: "{{ !input s2_active }}"
          - condition: template
            value_template: "{{ !input s2_t2_enabled }}"
          - condition: time
            weekday: !input s2_weekdays
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: !input climate_targets
            data:
              hvac_mode: !input s2_hvac_mode
              temperature: !input s2_t2_temp

      - conditions:
          - condition: trigger
            id: s2_t3
          - condition: template
            value_template: "{{ !input s2_active }}"
          - condition: template
            value_template: "{{ !input s2_t3_enabled }}"
          - condition: time
            weekday: !input s2_weekdays
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: !input climate_targets
            data:
              hvac_mode: !input s2_hvac_mode
              temperature: !input s2_t3_temp

      - conditions:
          - condition: trigger
            id: s2_t4
          - condition: template
            value_template: "{{ !input s2_active }}"
          - condition: template
            value_template: "{{ !input s2_t4_enabled }}"
          - condition: time
            weekday: !input s2_weekdays
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: !input climate_targets
            data:
              hvac_mode: !input s2_hvac_mode
              temperature: !input s2_t4_temp

      # -----------------------
      # Schedule 3 Actions
      # -----------------------
      - conditions:
          - condition: trigger
            id: s3_t1
          - condition: template
            value_template: "{{ !input s3_active }}"
          - condition: template
            value_template: "{{ !input s3_t1_enabled }}"
          - condition: time
            weekday: !input s3_weekdays
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: !input climate_targets
            data:
              hvac_mode: !input s3_hvac_mode
              temperature: !input s3_t1_temp

      - conditions:
          - condition: trigger
            id: s3_t2
          - condition: template
            value_template: "{{ !input s3_active }}"
          - condition: template
            value_template: "{{ !input s3_t2_enabled }}"
          - condition: time
            weekday: !input s3_weekdays
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: !input climate_targets
            data:
              hvac_mode: !input s3_hvac_mode
              temperature: !input s3_t2_temp

      - conditions:
          - condition: trigger
            id: s3_t3
          - condition: template
            value_template: "{{ !input s3_active }}"
          - condition: template
            value_template: "{{ !input s3_t3_enabled }}"
          - condition: time
            weekday: !input s3_weekdays
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: !input climate_targets
            data:
              hvac_mode: !input s3_hvac_mode
              temperature: !input s3_t3_temp

      - conditions:
          - condition: trigger
            id: s3_t4
          - condition: template
            value_template: "{{ !input s3_active }}"
          - condition: template
            value_template: "{{ !input s3_t4_enabled }}"
          - condition: time
            weekday: !input s3_weekdays
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: !input climate_targets
            data:
              hvac_mode: !input s3_hvac_mode
              temperature: !input s3_t4_temp
